# Generated by Django 3.2.8 on 2021-10-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_itemimages_item'),
        ('accounts', '0003_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.shop'),
        ),
    ]
