# Generated by Django 3.2.8 on 2021-10-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_info_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='shop',
        ),
    ]
